table 'ctg-studies (1)'
	lineageTag: e0962fa7-3d29-4208-92b9-a3f8e05e5c94

	column 'NCT Number'
		dataType: string
		lineageTag: 18b130c4-cc65-4fcf-bcb6-2559987cc2d2
		summarizeBy: none
		sourceColumn: NCT Number

		annotation SummarizationSetBy = Automatic

	column 'Study Title'
		dataType: string
		lineageTag: 425914d4-2b44-410e-9374-bbe1823ff71a
		summarizeBy: none
		sourceColumn: Study Title

		annotation SummarizationSetBy = Automatic

	column 'Study Status'
		dataType: string
		lineageTag: 10d5b1e0-9bd6-4c1d-b016-b62f61c3c3a7
		summarizeBy: none
		sourceColumn: Study Status

		annotation SummarizationSetBy = Automatic

	column 'Study Results'
		dataType: string
		lineageTag: d4518105-0698-460a-8f20-34c39b5fe579
		summarizeBy: none
		sourceColumn: Study Results

		annotation SummarizationSetBy = Automatic

	column Conditions
		dataType: string
		lineageTag: 48f86fd5-1b28-4499-be97-1aa436fa0a15
		summarizeBy: none
		sourceColumn: Conditions

		annotation SummarizationSetBy = Automatic

	column Interventions
		dataType: string
		lineageTag: f84fe58e-a970-4e1a-8de4-e763fb54fd0a
		summarizeBy: none
		sourceColumn: Interventions

		annotation SummarizationSetBy = Automatic

	column 'Primary Outcome Measures'
		dataType: string
		lineageTag: e1c288a8-3c43-474e-80b7-e24ba4429c82
		summarizeBy: none
		sourceColumn: Primary Outcome Measures

		annotation SummarizationSetBy = Automatic

	column Sponsor
		dataType: string
		lineageTag: 9fd2ec25-17b1-4990-be48-e812081ab1a1
		summarizeBy: none
		sourceColumn: Sponsor

		annotation SummarizationSetBy = Automatic

	column Collaborators
		dataType: string
		lineageTag: d9f7cdf5-05d0-48a4-b495-959c2bd61f75
		summarizeBy: none
		sourceColumn: Collaborators

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: 8f0f51e7-ee5b-412a-aa68-e4a3d8a3d7a8
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: string
		lineageTag: d117a178-eae6-4dd8-a466-194bed98083d
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Phases
		dataType: string
		lineageTag: 4cf8fcff-f205-4e36-a7e3-1bd1899ccda6
		summarizeBy: none
		sourceColumn: Phases

		annotation SummarizationSetBy = Automatic

	column Enrollment
		dataType: int64
		formatString: 0
		lineageTag: ad15e555-347f-4248-9915-44068f545cd3
		summarizeBy: sum
		sourceColumn: Enrollment

		annotation SummarizationSetBy = Automatic

	column 'Funder Type'
		dataType: string
		lineageTag: a393b993-9eb4-4601-8200-b9363168bc02
		summarizeBy: none
		sourceColumn: Funder Type

		annotation SummarizationSetBy = Automatic

	column 'Study Type'
		dataType: string
		lineageTag: 6df17e7a-f28e-4cd8-bc92-d1d28afa1851
		summarizeBy: none
		sourceColumn: Study Type

		annotation SummarizationSetBy = Automatic

	column 'Study Design'
		dataType: string
		lineageTag: 9963c377-c856-4a85-a967-87c332cb65be
		summarizeBy: none
		sourceColumn: Study Design

		annotation SummarizationSetBy = Automatic

	column 'Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a0db4105-3d12-4860-b05e-85b1a95f1ce9
		summarizeBy: none
		sourceColumn: Start Date

		variation Variation
			isDefault
			relationship: eddb186e-3ff4-4e59-a083-fa6c2323fa73
			defaultHierarchy: LocalDateTable_13581c59-80a2-4875-889f-1313dd25bbdd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Primary Completion Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: df3fd8bb-a84a-49c0-8e39-75747e2505d5
		summarizeBy: none
		sourceColumn: Primary Completion Date

		variation Variation
			isDefault
			relationship: 9d44d311-7966-4f0b-9ef8-94e8e1253b3d
			defaultHierarchy: LocalDateTable_26d89c63-7b41-49c2-9c71-b4997093c344.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Completion Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 747aa0da-a3b9-4f74-8a5a-f6aaed701ded
		summarizeBy: none
		sourceColumn: Completion Date

		variation Variation
			isDefault
			relationship: 8e91f17f-afc8-4a1e-9a7c-4b00d7a37fcd
			defaultHierarchy: LocalDateTable_a87b7651-c2b5-41b5-a190-159bb3f4f7f2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Results First Posted'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 898634cb-5645-4d02-8fd3-d704955e3964
		summarizeBy: none
		sourceColumn: Results First Posted

		variation Variation
			isDefault
			relationship: cdeb060c-b1e0-4a21-96fc-f930d9e59c57
			defaultHierarchy: LocalDateTable_c7ba7622-9143-464b-8259-8aa178541593.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Locations
		dataType: string
		lineageTag: 4704d318-5fc2-4946-b966-8e95f5e4acef
		summarizeBy: none
		sourceColumn: Locations

		annotation SummarizationSetBy = Automatic

	column Year = YEAR('ctg-studies (1)'[Start Date])
		dataType: int64
		formatString: 0
		lineageTag: b3f35376-3cb3-4e77-b795-c934114e6fe7
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition 'ctg-studies (1)' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Personal Doc\Interview Prep\ClinicalTrial\ctg-studies (1).csv"),[Delimiter=",", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"NCT Number", type text}, {"Study Title", type text}, {"Study Status", type text}, {"Study Results", type text}, {"Conditions", type text}, {"Interventions", type text}, {"Primary Outcome Measures", type text}, {"Sponsor", type text}, {"Collaborators", type text}, {"Sex", type text}, {"Age", type text}, {"Phases", type text}, {"Enrollment", Int64.Type}, {"Funder Type", type text}, {"Study Type", type text}, {"Study Design", type text}, {"Start Date", type date}, {"Primary Completion Date", type date}, {"Completion Date", type date}, {"Results First Posted", type date}, {"Locations", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Study Status] <> "ACTIVE_NOT_RECRUITING" and [Study Status] <> "APPROVED_FOR_MARKETING" and [Study Status] <> "ENROLLING_BY_INVITATION" and [Study Status] <> "NOT_YET_RECRUITING" and [Study Status] <> "NO_LONGER_AVAILABLE")),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","","NA",Replacer.ReplaceValue,{"Phases"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

